import type { Strings } from './zh-TW.js'

export const en: Strings = {
  toc: 'Contents',
  chapters: {
    overview: 'Overview',
    'tech-stack': 'Tech Stack',
    architecture: 'Architecture',
    'user-stories': 'User Stories',
    roadmap: 'Roadmap',
  },
  labels: {
    as: 'As a',
    soThat: 'so that',
    layer: 'Layer',
  },
  statuses: {
    done: 'Done',
    active: 'In Progress',
    future: 'Planned',
  },
  footer: 'Generated by SpecBook',
  docs: {
    user: {
      invalidDocKey: (locale: string, file: string, key: string) =>
        `[docs.user.invalidDocKey] ${locale}/${file}: doc-key "${key}" has invalid format (must be kebab-case [a-z0-9-]+)`,
      duplicateDocKey: (locale: string, file: string, key: string) =>
        `[docs.user.duplicateDocKey] ${locale}/${file}: doc-key "${key}" appears more than once`,
      missingDocKey: (locale: string, key: string) =>
        `[docs.user.missingDocKey] ${locale}: missing required doc-key "${key}"`,
      orderMismatch: (
        locale: string,
        position: number,
        md: string | undefined,
        html: string | undefined,
      ) =>
        `[docs.user.orderMismatch] ${locale}: md/html doc-key order diverges at position ${position}\n  index.md  position ${position}: ${md ?? '(none)'}\n  index.html position ${position}: ${html ?? '(none)'}`,
      localeDriftDocKey: (
        locale: string,
        missing: readonly string[],
        extra: readonly string[],
      ) =>
        `[docs.user.localeDriftDocKey] ${locale}: doc-key set differs from other locales\n  missing: ${missing.join(', ') || '(none)'}\n  extra: ${extra.join(', ') || '(none)'}`,
      missingFile: (locale: string, path: string) =>
        `[docs.user.missingFile] ${locale}: required file missing: ${path}`,
    },
  },
}
