import type { Strings } from './zh-TW.js'

export const en: Strings = {
  toc: 'Contents',
  chapters: {
    overview: 'Overview',
    'tech-stack': 'Tech Stack',
    architecture: 'Architecture',
    'user-stories': 'User Stories',
    roadmap: 'Roadmap',
  },
  labels: {
    as: 'As a',
    soThat: 'so that',
    layer: 'Layer',
  },
  statuses: {
    done: 'Done',
    active: 'In Progress',
    future: 'Planned',
  },
  footer: 'Generated by SpecBook',
}
