export const zhTW = {
  toc: '目錄',
  chapters: {
    overview: 'Overview',
    'tech-stack': 'Tech Stack',
    architecture: 'Architecture',
    'user-stories': 'User Stories',
    roadmap: 'Roadmap',
  },
  labels: {
    as: '身為',
    soThat: '以便',
    layer: '層',
  },
  statuses: {
    done: '完成',
    active: '進行中',
    future: '規劃',
  },
  footer: 'Generated by SpecBook',
}

export type Strings = typeof zhTW
