export const zhTW = {
  toc: '目錄',
  chapters: {
    overview: 'Overview',
    'tech-stack': 'Tech Stack',
    architecture: 'Architecture',
    'user-stories': 'User Stories',
    roadmap: 'Roadmap',
  },
  labels: {
    as: '身為',
    soThat: '以便',
    layer: '層',
  },
  statuses: {
    done: '完成',
    active: '進行中',
    future: '規劃',
  },
  footer: 'Generated by SpecBook',
  docs: {
    user: {
      invalidDocKey: (locale: string, file: string, key: string) =>
        `[docs.user.invalidDocKey] ${locale}/${file}: doc-key "${key}" 格式不合法（需為 kebab-case [a-z0-9-]+）`,
      duplicateDocKey: (locale: string, file: string, key: string) =>
        `[docs.user.duplicateDocKey] ${locale}/${file}: doc-key "${key}" 重複出現`,
      missingDocKey: (locale: string, key: string) =>
        `[docs.user.missingDocKey] ${locale}: 缺少 required doc-key "${key}"`,
      orderMismatch: (
        locale: string,
        position: number,
        md: string | undefined,
        html: string | undefined,
      ) =>
        `[docs.user.orderMismatch] ${locale}: md/html doc-key 順序在位置 ${position} 不一致\n  index.md  位置 ${position}: ${md ?? '(無)'}\n  index.html 位置 ${position}: ${html ?? '(無)'}`,
      localeDriftDocKey: (
        locale: string,
        missing: readonly string[],
        extra: readonly string[],
      ) =>
        `[docs.user.localeDriftDocKey] ${locale}: 與其他 locale 的 doc-key 集合不一致\n  缺少: ${missing.join(', ') || '(無)'}\n  多餘: ${extra.join(', ') || '(無)'}`,
      missingFile: (locale: string, path: string) =>
        `[docs.user.missingFile] ${locale}: 缺少必要檔案 ${path}`,
    },
  },
}

export type Strings = typeof zhTW
